---
- name: Copiar credenciales AWS a la EC2
  hosts: terraform-runner
  become: no
  vars:
    aws_credentials_src: ~/.aws/credentials
    aws_config_src: ~/.aws/config
    aws_dir_dest: ~/.aws

  tasks:

    - name: Crear carpeta .aws en el host remoto
      file:
        path: "{{ aws_dir_dest }}"
        state: directory
        mode: '0700'

    - name: Copiar archivo credentials
      copy:
        src: "{{ aws_credentials_src }}"
        dest: "{{ aws_dir_dest }}/credentials"
        mode: '0600'

    - name: Copiar archivo config (opcional)
      copy:
        src: "{{ aws_config_src }}"
        dest: "{{ aws_dir_dest }}/config"
        mode: '0600'
      ignore_errors: yes
