---
- name: Setup para el uso de playbooks Ansible con Terraform y AWS
  hosts: localhost
  #become: yes
  vars:
    aws_credentials_src: ~/.aws/credentials
    aws_config_src: ~/.aws/config
    aws_dir_dest: ~/.aws
    aws_cli_version: "2.13.15"  # Puedes cambiar a la versión que quieras

  tasks:

    - name: Instalar git si no está instalado
      package:
        name: git
        state: present

    - name: Crear carpeta .aws en el host remoto
      file:
        path: "{{ aws_dir_dest }}"
        state: directory
        mode: '0700'

    - name: Copiar archivo credentials
      copy:
        src: "{{ aws_credentials_src }}"
        dest: "{{ aws_dir_dest }}/credentials"
        mode: '0600'

    - name: Copiar archivo config (opcional)
      copy:
        src: "{{ aws_config_src }}"
        dest: "{{ aws_dir_dest }}/config"
        mode: '0600'
      ignore_errors: yes

    - name: Instalar pip3 si no está instalado
      package:
        name: python3-pip
        state: present

    - name: Instalar boto3 y botocore
      pip:
        name:
          - boto3
          - botocore

    - name: Instalar colección amazon.aws en el host remoto
      shell: ansible-galaxy collection install amazon.aws
      args:
        executable: /bin/bash

    - name: Descargar instalador AWS CLI
      get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-{{ aws_cli_version }}.zip"
        dest: "/tmp/awscliv2.zip"
        mode: '0644'

    - name: Instalar unzip si no está instalado
      package:
        name: unzip
        state: present

    - name: Descomprimir instalador AWS CLI
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: yes
        creates: /tmp/aws

    - name: Instalar AWS CLI
      command: /tmp/aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
      args:
        creates: /usr/local/bin/aws

    - name: Verificar instalación AWS CLI
      command: aws --version
      register: awscli_version
      changed_when: false

    - name: Mostrar versión instalada de AWS CLI
      debug:
        var: awscli_version.stdout
