---
- name: Clonar repositorio Terraform en la EC2
  hosts: terraform-runner
  become: yes
  vars:
    remote_terraform_dir: /home/ubuntu/infra
    repo_url: 'https://github.com/avilamowski/tpe-redes-g4'
    repo_version: 'main'  # rama o tag a clonar

  tasks:

    - name: Asegurar directorio destino en la EC2
      file:
        path: "{{ remote_terraform_dir }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Clonar o actualizar repositorio Git
      git:
        repo: "{{ repo_url }}"
        dest: "{{ remote_terraform_dir }}"
        version: "{{ repo_version }}"
        update: yes
        force: yes
        accept_hostkey: yes
      become_user: ubuntu
