---
- name: Launch EC2 instance using AWS Lambda
  hosts: local 
  gather_facts: no

  vars:
    # default to 0 hours delay if not specified
    delay_hours: 0
    subnet_id: ""
    api_url_launch: ""

  tasks:
    - name: Wait before launching EC2 instance
      ansible.builtin.pause:
        seconds: "{{ delay_hours | int * 3600 }}"
      when: delay_hours | int > 0

    - name: Send POST request to Lambda
      uri:
        url: "{{ api_url_launch  }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body:
          instance_type: "{{ instance_type }}"
          subnet_id: "{{ subnet_id }}"
        body_format: json
        return_content: yes
      register: response

    - name: Display Lambda response
      debug:
        var: response.content
