---
- name: Setup para el uso de playbooks Ansible con Terraform y AWS
  hosts: terraform-runner
  become: yes
  vars:
    aws_credentials_src: ~/.aws/credentials
    aws_config_src: ~/.aws/config
    aws_dir_dest: ~/.aws

  tasks:

    - name: Crear carpeta .aws en el host remoto
      file:
        path: "{{ aws_dir_dest }}"
        state: directory
        mode: '0700'

    - name: Copiar archivo credentials
      copy:
        src: "{{ aws_credentials_src }}"
        dest: "{{ aws_dir_dest }}/credentials"
        mode: '0600'

    - name: Copiar archivo config (opcional)
      copy:
        src: "{{ aws_config_src }}"
        dest: "{{ aws_dir_dest }}/config"
        mode: '0600'
      ignore_errors: yes

    - name: Instalar pip3 si no está instalado
      package:
        name: python3-pip
        state: present

    - name: Instalar boto3 y botocore
      pip:
        name:
          - boto3
          - botocore

    - name: Instalar colección amazon.aws en el host remoto
      shell: |
        ansible-galaxy collection install amazon.aws
      args:
        executable: /bin/bash
