---
- name: Invoke AWS Lambda to stop/delete EC2 instance
  hosts: localhost
  gather_facts: no

  vars:
    ec2_instance_id: ""   # Pass this as an extra var on AWX launch 

  tasks:
    - name: Call Lambda API to stop/delete EC2
      uri:
        url: "{{ api_url_kill }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body: "{{ {'instance_id': ec2_instance_id} | to_json }}"
        body_format: raw
        status_code: 200
      register: lambda_response

    - name: Show Lambda response
      debug:
        var: lambda_response.msg
