---
- name: Dar de baja una instancia EC2 en AWS
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    region: us-east-1  # Region de AWS
    aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"

  tasks:
    - name: Terminate EC2
      amazon.aws.ec2_instance:
        state: absent
        instance_ids: "{{ instance_id }}"
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: termination_result

    - name: Show termination result
      debug:
        var: termination_result
