---
- name: Update firewall rules on EC2 instance
  hosts: local
  become: yes

  tasks:
    - name: Ensure firewalld is installed and running
      apt:
        name: firewalld
        state: present
        update_cache: yes

    - name: Enable and start firewalld
      systemd:
        name: firewalld
        enabled: yes
        state: started

    - name: Add firewalld services (open ports)
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop: "{{ open_services }}"
      when: open_services is defined and open_services | length > 0

    - name: Remove firewalld services (close ports)
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: disabled
        immediate: yes
      loop: "{{ close_services }}"
      when: close_services is defined and close_services | length > 0

    - name: Reload firewalld to apply changes
      command: firewall-cmd --reload
      when: (open_services | length > 0) or (close_services | length > 0)
