---
- name: Manage firewalld rules on web1 via AWX
  hosts: ubuntu
  become: yes

  vars:
    open_services: []
    close_services: []

  tasks:
    - name: Ensure firewalld is installed
      package:
        name: firewalld
        state: present

    - name: Ensure firewalld is enabled and running
      systemd:
        name: firewalld
        state: started
        enabled: yes

    - name: Open firewalld services
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop: "{{ open_services }}"
      when: open_services | length > 0

    - name: Close firewalld services
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: disabled
        immediate: yes
      loop: "{{ close_services }}"
      when: close_services | length > 0

    - name: Reload firewalld
      command: firewall-cmd --reload
      when: (open_services | length > 0) or (close_services | length > 0)
