---
- name: Manage firewalld rules on web1 via AWX
  hosts: ubuntu
  become: yes          

  vars:
    open_services: []
    close_services: []

  tasks:
    - name: Check if firewalld is installed
        command: rpm -q firewalld
        register: firewalld_check
        ignore_errors: yes
        changed_when: false

    - name: Install firewalld if not installed
      package:
        name: firewalld
        state: present
      when: firewalld_check.rc != 0

    - name: Open firewalld services
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop: "{{ open_services }}"
      when: open_services | length > 0

    - name: Close firewalld services
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: disabled
        immediate: yes
      loop: "{{ close_services }}"
      when: close_services | length > 0

    - name: Reload firewalld
      command: firewall-cmd --reload
      when: (open_services | length > 0) or (close_services | length > 0)

    - name: Confirm playbook completed successfully
      debug:
        msg: "✅ Firewalld configuration completed successfully"
