---
- name: Deploy website on EC2 instances
  hosts: webservers
  become: yes
  vars:
    aws_region: "{{ hostvars[inventory_hostname]['aws_region'] }}"
    zip_file_url: ""
    web_folder: ""

  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        update_cache: yes
        name:
          - nginx
          - unzip
          - wget
          - firewalld
        state: present

    - name: Download zip file from S3
      ansible.builtin.get_url:
        url: "{{ zip_file_url }}"
        dest: "/tmp/web.zip"

    - name: Extract website files
      ansible.builtin.unarchive:
        src: "/tmp/web.zip"
        dest: "/tmp/unzipped/"
        remote_src: yes
        creates: yes

    - name: Delete existing files in /var/www/html
      ansible.builtin.file:
        path: "/var/www/html/"
        state: absent
    
    - name: Copy website files into /var/www/html
      ansible.builtin.copy:
        src: "/tmp/unzipped/{{ web_folder }}/"
        dest: "/var/www/html/"
        remote_src: yes

    - name: Set ownership and permissions on /var/www/html
      ansible.builtin.file:
        path: /var/www/html
        owner: www-data
        group: www-data
        recurse: yes
        mode: "0777"

    - name: Enable and start nginx
      ansible.builtin.systemd:
        name: nginx
        enabled: yes
        state: started

    - name: Configure firewalld to allow HTTP and HTTPS
      ansible.builtin.firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - http
        - https

    - name: Enable and start firewalld
      ansible.builtin.systemd:
        name: firewalld
        enabled: yes
        state: started

    - name: Delete downloaded zip file
      ansible.builtin.file:
        path: "/tmp/web.zip"
        state: absent

    - name: Delete unzipped files
      ansible.builtin.file:
        path: "/tmp/unzipped/"
        state: absent