---
- name: Deploy website on EC2 instances
  hosts: webservers
  become: yes
  vars:
    aws_region: "{{ hostvars[inventory_hostname]['aws_region'] }}"
    zip_file_url: ""
    web_folder: ""

  tasks:
    - name: Install required packages
      apt:
        update_cache: yes
        name:
          - nginx
          - unzip
          - wget
          - firewalld
        state: present

    - name: Download zip file from S3
      get_url:
        url: "{{ zip_file_url }}"
        dest: "/tmp/web.zip"

    - name: Extract website files
      unarchive:
        src: "/tmp/web.zip"
        dest: "/tmp/"
        remote_src: yes
    
    - name: Copy website files
      copy:
        src: "/tmp/{{ web_folder }}/"
        dest: "/var/www/html/"
        remote_src: yes

    - name: Set ownership and permissions on /var/www/html
      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        recurse: yes
        mode: "0777"

    - name: Enable and start nginx
      systemd:
        name: nginx
        enabled: yes
        state: started

    - name: Configure firewalld to allow HTTP and HTTPS
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - http
        - https

    - name: Enable and start firewalld
      systemd:
        name: firewalld
        enabled: yes
        state: started